version: "3.7"
services:
  golang-blueprint-clean-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    container_name: golang-blueprint-clean
    command:  sh -c 'wait-for postgres-customer-db:5432 --timeout=60 && cd app && GO111MODULE=on fresh'
    restart: 'always'
    volumes:
    - ../..:/go/src/golang-blueprint-clean
    ports:
    - "8080:8080"
    environment:
      POSTGRES_HOST: postgres-customer-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: customers_db

  postgres-customer-db:
    image: "postgres:9.5-alpine"
    container_name: postgres-customer-db
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: 'always'
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: customers_db

  pgadmin:
    image: chorss/docker-pgadmin4
    logging:
      driver: "none"
    depends_on:
      - postgres-customer-db
    ports:
      - 5050:5050

  admin:
    image: adminer
    container_name: db-admin
    ports:
      - "5544:8080"
