version: "3.7"
services:
  golang-blueprint-clean-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    container_name: golang-blueprint-clean
    command:  sh -c 'cd app && GO111MODULE=on fresh'
    restart: 'always'
    volumes:
    - ../..:/go/src/golang-blueprint-clean
    ports:
    - "8080:8080"
    environment:
      ORACLE_HOST: localhost:1521/orcl
      ORACLE_USER: system
      ORACLE_PASSWORD: tiger