// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/layers/usecases/customer/init.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "golang-blueprint-clean/app/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateRole mocks base method.
func (m *MockUseCase) CreateRole(input *entities.Roles) (*entities.Roles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", input)
	ret0, _ := ret[0].(*entities.Roles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockUseCaseMockRecorder) CreateRole(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockUseCase)(nil).CreateRole), input)
}

// CreateUser mocks base method.
func (m *MockUseCase) CreateUser(input *entities.Users) (*entities.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", input)
	ret0, _ := ret[0].(*entities.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUseCaseMockRecorder) CreateUser(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUseCase)(nil).CreateUser), input)
}

// FindOneUserData mocks base method.
func (m *MockUseCase) FindOneUserData(input *entities.UsersFilter) (*entities.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneUserData", input)
	ret0, _ := ret[0].(*entities.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneUserData indicates an expected call of FindOneUserData.
func (mr *MockUseCaseMockRecorder) FindOneUserData(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneUserData", reflect.TypeOf((*MockUseCase)(nil).FindOneUserData), input)
}
