// Code generated by MockGen. DO NOT EDIT.
// Source: E:\golang-project\golang-blueprint-clean\app\layers\repositories\back_office\init.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "golang-blueprint-clean/app/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// FindBanners mocks base method.
func (m *MockRepo) FindBanners(segment string) ([]entities.Banners, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBanners", segment)
	ret0, _ := ret[0].([]entities.Banners)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBanners indicates an expected call of FindBanners.
func (mr *MockRepoMockRecorder) FindBanners(segment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBanners", reflect.TypeOf((*MockRepo)(nil).FindBanners), segment)
}
