// Code generated by MockGen. DO NOT EDIT.
// Source: E:\golang-project\golang-blueprint-clean\app\layers\usecases\back_office\init.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "golang-blueprint-clean/app/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// FindBanners mocks base method.
func (m *MockUseCase) FindBanners(segment string) ([]entities.Banners, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBanners", segment)
	ret0, _ := ret[0].([]entities.Banners)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBanners indicates an expected call of FindBanners.
func (mr *MockUseCaseMockRecorder) FindBanners(segment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBanners", reflect.TypeOf((*MockUseCase)(nil).FindBanners), segment)
}
